version: 2
updates:
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
- package-ecosystem: pip
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
- package-ecosystem: github-actions
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
