name: publish
on:
  release:
    types:
      - published

env:
  PYTHON_VERSION: 3.x

jobs:
  publish_pypi:
    name: Build and push Python package
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Set up Python runtime
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Python dependencies
        run: pip install --upgrade setuptools wheel twine

      - name: Build Python package
        run: python setup.py build sdist bdist_wheel --universal

      - name: Publish Python package
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --disable-progress-bar -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*

  publish_docker:
    name: Build and push Docker image
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          tags: |
            ${{ github.event.repository.full_name }}:latest
            ${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.event.repository.full_name }}:latest
            ghcr.io/${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}

      - name: Check Docker image
        run:
          docker run --rm -i -v ${PWD}:/docs ${{ github.event.repository.full_name }} build

      - name: Publish Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker push --all-tags ${{ github.event.repository.full_name }}
          docker push --all-tags ghcr.io/${{ github.event.repository.full_name }}
